# Generated by Django 2.1.7 on 2019-02-22 21:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mgmt', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_by_id', to='mgmt.Employees')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to_id', to='mgmt.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sticket.Assignments')),
            ],
        ),
        migrations.CreateModel(
            name='StatusesList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_name', models.CharField(max_length=50)),
                ('ticket_description', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sticket.Categories')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mgmt.Employees')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mgmt.Departments')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mgmt.Properties')),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_id', to='sticket.StatusesList'),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mgmt.Employees'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sticket.Tickets'),
        ),
    ]
